# Setup
title:        Overfeeding
tagline:      Putama's learning notes
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Prasetya Utama
  url:        http://putama.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
